<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MarkdownSnippets.MsBuild">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="MSTest" />
    <PackageReference Include="Verify.MSTest" />
    <PackageReference Include="XenoAtom.Terminal.UI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XenoAtom.CommandLine\XenoAtom.CommandLine.csproj" />
    <ProjectReference Include="..\XenoAtom.CommandLine.Terminal\XenoAtom.CommandLine.Terminal.csproj" />
  </ItemGroup>
</Project>
