<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="MinVer" Version="5.0.0" />
    <PackageVersion Include="Verify.MSTest" Version="24.1.0" />
    <PackageVersion Include="MSTest" Version="4.0.2" />
  </ItemGroup>
</Project>
